### ISSUE TITLE
Repo has no initial branch for exercises

### ISSUE THREAD

**Issue by flaviuse** [onehungrymind/fem-enterprise-patterns#3]
Hello,
The main is already completed with solutions, can you please add a branch so we can do the exercises.
Thank you have a nice day

**Comment by davidhousedev** [comment]
To add a little more color here, it looks like cffebc49f3c5722cd17d982202e991132409836b committed the solution of the micro refactoring exercise to the location where the video tells us to solve the exercise. In order to follow along with the video, I had to make some changes to the repo locally to revert the changes to `apps/micro/src/app/home/home.component.ts`.

**Comment by flaviuse** [comment]
Branch has been added
